domain: eticcista.github.io
url: https://eticcista.github.io
baseurl: ""

title: EtiCCista
email: eticcista@gmail.com
author: acsd

lang: pt

plugins:
  - jekyll-seo-tag

color: "#ff006e"
# disqus:
#   shortname: example-com
#
rrss:
  email: "eticcista@gmail.com"